exchange: binance
symbol: BTC/USDT
timeframes:
  # - 1m
  - 5m
  - 15m
  - 1h
  - 4h
  - 1d
rsi_period: 14
# future_periods:
#   '1m': 
#     - 5 
#     - 15
#     - 30
#     - 60
#   '5m':
#     - 3
#     - 6
#     - 12
#     - 24
#     - 48
#   '15m':
#     - 2
#     - 4
#     - 8
#     - 16
#     - 32
#     - 48
#   '1h':
#     - 4
#     - 8
#     - 12
#     - 24
#   '4h':
#     - 2 
#     - 3
#     - 6
#     - 12
#     - 18
#   '1d':
#     - 2
#     - 3
#     - 7
#     - 14
#     - 21